strassen_all:
	gcc -lm strassen_matrix_multiplication.c -o strassen_exec
	./strassen_exec
	rm -rf strassen_exec

lim_all:
	gcc -lm large_integer_multiplication.c -o lim_exec
	./lim_exec
	rm -rf lim_exec

sort_all:
	gcc -lm heap_radix_sort.c -o sort_exec
	./sort_exec
	rm -rf sort_exec
